apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    url: https://{{ grains.master }}:8086
    jsonData:
      tlsAuth: true
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: "/etc/pki/ca.crt"
      tlsClientCert: "/etc/pki/grafana.crt"
      tlsClientKey: "/etc/pki/grafana.key"
    version: 1
