{%- set freq = salt['pillar.get']('master:freq', '0') %}
{%- set domainstats = salt['pillar.get']('master:domainstats', '0') %}
- pipeline.id: sodefault
  path.config: "/usr/share/logstash/pipeline"
  queue.type: persisted
- pipline.id: custom
  path.config: "/usr/share/logstash/custom"
  queue.type: persisted
{%- if freq == '1' %}
- pipeline.id: freq
  path.config: "/usr/share/logstash/freq"
  queue.type: persisted
{%- if domainstats == '1' %}
- pipeline.id: domainstats
  path.config: "/usr/share/logstash/domainstats"
  queue.type: persisted
{%- endif %}
