{%- set freq = salt['pillar.get']('master:freq', '0') %}
{%- set domainstats = salt['pillar.get']('master:domainstats', '0') %}
- pipeline.id: sodefault
  path.config: "/usr/share/logstash/pipeline"
- pipeline.id: custom
  path.config: "/usr/share/logstash/custom"
{%- if freq == '1' %}
- pipeline.id: freq
  path.config: "/usr/share/logstash/freq"
{%- if domainstats == '1' %}
- pipeline.id: domainstats
  path.config: "/usr/share/logstash/domainstats"
{%- endif %}
